name: flutterdemo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker:
  video_player:
  audioplayers:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/flutter.png
   - assets/im.png
   - assets/share.png
   - assets/ums.png
   - assets/zx@3x.png
   - assets/wd@3x.png
   - assets/zx_02@3x.png
   - assets/wd_02@3x.png
   - assets/back.png
   - assets/message_left.png
   - assets/message_right.png
   - assets/service.png
   - assets/star_l.png
   - assets/star.png
   - assets/keyboard.png
   - assets/add.png
   - assets/emoj.png
   - assets/imtable/im_file.png
   - assets/imtable/im_jankenpo.png
   - assets/imtable/im_media.png
   - assets/imtable/im_position.png
   - assets/imtable/im_receipt.png
   - assets/imtable/im_redpacket.png
   - assets/imtable/im_shoot.png
   - assets/imtable/im_tmp.png
   - assets/imtable/im_voice.png
   - assets/im_row.png
   - assets/im_star_0.png
   - assets/im_star_1.png
   - assets/im_player.png
   - assets/imtable/daoshu.mp4
   - assets/im_sound@2x.png
   - assets/im_sound_1@2x.png
   - assets/msg_recv_voice_1.png
   - assets/msg_recv_voice_2.png
   - assets/msg_recv_voice_3.png
   - assets/msg_recv_voice_4.png
   - assets/msg_send_voice_1.png
   - assets/msg_send_voice_2.png
   - assets/msg_send_voice_3.png
   - assets/msg_send_voice_4.png
   - assets/OurMemory.mp3
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
